apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server
  labels:
    app: server
spec:
  minReplicas: 2
  maxReplicas: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  targetCPUUtilizationPercentage: 85
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: hamonangann/thesis-app
        resources:
          requests:
            cpu: 2
          limits:
            cpu: 2
        ports:
          - containerPort: 8000
        env:
          - name: CPUS
            value: "2"